// Generated by CoffeeScript 1.6.3
exports.require = ["http.server", "express"];

exports.load = function(server, express) {
  return server.use("/vendor", express["static"](__dirname + "/vendor"));
};

