include ../../../makefile.inc

#-----------------------------------------------------------


# source dir
SDIR = ./src


BDIR = ../../apps/desktop_player/bin


#-----------------------------------------------------------

all: player


player: 
	../../../compilers/as3/bin/mxmlc $(SDIR)/DesktopPlayer.as -o $(BDIR)/DesktopPlayer.swf

