include ../../../makefile.inc

#-----------------------------------------------------------


# source dir
SDIR = ./src


BDIR = ../site/_assets/flash


#-----------------------------------------------------------

all: player


player: 
	../../../compilers/as3/bin/mxmlc $(SDIR)/DesktopPlayer.as -o $(BDIR)/DesktopPlayer.swf

