// Generated by CoffeeScript 1.6.3
var packages;

packages = require("packages");

module.exports = function(type) {
  process.env.TYPE = type;
  console.log("starting " + type);
  return packages().require(__dirname + "/common").require(__dirname + "/" + type).load();
};
