include ../makefile.inc

#-----------------------------------------------------------


# source dir
SDIR = ./src




#-----------------------------------------------------------

all: player


player: 
	/Applications/Adobe\ Flash\ Builder\ 4/sdks/4.6.0/bin/mxmlc $(SDIR)/DesktopPlayer.as -o ./bin/DesktopPlayer.swf
	cp ./bin/DesktopPlayer.swf ../application/lib/plugins/http.client/public/swf

