// Generated by CoffeeScript 1.6.3
exports.require = ["config", "mongoose"];

exports.load = function(config, mongoose) {
  var inf;
  inf = config.get("mongodb");
  return mongoose.connect("mongodb://" + inf.host + ":" + inf.port + "/" + inf.db);
};

