# Do not edit. File was generated by pangyp's 'configure' step
{
  'variables': {
    'use_openssl': 0,
    'os_posix': 1,
    'clang': 1,
    'lsan': 1,
    'tsan': 1,
    'host_arch': 'x64',
    # 'python': '/usr/bin/python',
    'target_arch': 'x64',
    'standalone_static_library': 1
  }
}
