// Generated by CoffeeScript 1.6.3
exports.require = ["config", "http.server", "passport", "express", "connect-mongo"];

exports.load = function(config, server, passport, express, connectMongo) {
  var MongoStore;
  MongoStore = connectMongo(express);
  server.use(express.session({
    cookie: {
      maxAge: 3600000
    },
    store: new MongoStore(config.get("mongodb"))
  }));
  return server.use(passport.session());
};

